version: '3.7'

services:
  sudo-bot:
    container_name: sudo-bot
    hostname: sudo-bot
    build: 
      context: .
      dockerfile: Dockerfile
    image: sudo-bot:0.0.1
    restart: on-failure
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
